import {
	Vulcan,
	HintOfRed,
	BlueGreen,
	MikadoYellow,
	Jasper,
	Eucalyptus,
	OsloGray,
	Azure,
	FrenchGray,
	DoveGray,
	Black,
	BlueDeFrance,
	White,
	Mischka,
	Hoki,
	SanJuan
} from './colors';

export default {
	primaryColor: Azure,
	primaryTextColor: Black,
	primaryBgColor: White,
	primaryItemBgColor: HintOfRed,
	secondaryItemColor: BlueGreen,
	secondaryTextColor: Vulcan,
	secondaryBgColor: FrenchGray,
	successColor: Eucalyptus,
	InfoColor: BlueGreen,
	errorColor: Jasper,
	warningColor: MikadoYellow,
	separatorColor: HintOfRed,
	borderColorBase: HintOfRed,
	black: Black,
	white: White,
};